name: firebolt-core

services:
  firebolt-core:
    image: ghcr.io/firebolt-db/firebolt-core:${IMAGE_TAG}
    container_name: firebolt-core
    command: --node 0
    privileged: true
    restart: no
    ulimits:
      memlock: 8589934592
    ports:
      - 3473:3473
    volumes:
      - ${BASE_DIR}/.github/resources/core/config.json:/firebolt-core/config.json:ro
      - ${BASE_DIR}/firebolt-core:/firebolt-core/data
