# This workflow will install Python dependencies, run pre-commit checks, and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-title:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check title name convention
        uses: jef/conventional-commits-pr-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  code-check:
    uses: ./.github/workflows/code-check.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  security-scan:
    needs: [unit-tests]
    uses: ./.github/workflows/security-scan.yml
    secrets:
      FOSSA_TOKEN: ${{ secrets.FOSSA_TOKEN }}
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
