name: v1 Integration tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_STG_USERNAME:
        required: true
      FIREBOLT_STG_PASSWORD:
        required: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@v1
        with:
          firebolt-username: ${{ secrets.FIREBOLT_STG_USERNAME }}
          firebolt-password: ${{ secrets.FIREBOLT_STG_PASSWORD }}
          api-endpoint: "api.staging.firebolt.io"
          region: "us-east-1"

      - name: Restore cached failed tests
        id: cache-tests-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .pytest_cache/v/cache/lastfailed
          key: ${{ runner.os }}-pytest-restore-failed-${{ github.ref }}-${{ github.sha }}-v1

      - name: Run integration tests
        env:
          # the distinction is on the SDK side so just use CLIENT_* for username password
          CLIENT_ID: ${{ secrets.FIREBOLT_STG_USERNAME }}
          CLIENT_SECRET: ${{ secrets.FIREBOLT_STG_PASSWORD }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          ENGINE_URL: ${{ steps.setup.outputs.engine_url }}
          STOPPED_ENGINE_NAME: ${{ steps.setup.outputs.stopped_engine_name }}
          STOPPED_ENGINE_URL: ${{ steps.setup.outputs.stopped_engine_url }}
          FIREBOLT_BASE_URL: "api.staging.firebolt.io"
          ACCOUNT_NAME: "firebolt"
        run: |
          pytest --last-failed -o log_cli=true -o log_cli_level=INFO tests/integration

      - name: Save failed tests
        id: cache-tests-save
        uses: actions/cache/save@v3
        if: failure()
        with:
          path: |
            .pytest_cache/v/cache/lastfailed
          key: ${{ steps.cache-tests-restore.outputs.cache-primary-key }}
