name: Core integration tests

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'The docker image tag for the firebolt core'
        required: false
        type: string
        default: 'preview-rc'
      python_version:
        description: 'Python version'
        required: false
        type: string
        default: '3.9'
  workflow_call:
    inputs:
      tag_version:
        description: 'The docker image tag for the firebolt core'
        required: false
        type: string
        default: 'preview-rc'
      python_version:
        description: 'Python version'
        required: false
        type: string
        default: '3.9'

jobs:
  run-core-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Firebolt Core
        id: setup-core
        uses: firebolt-db/action-setup-core@main
        with:
          tag_version: ${{ inputs.tag_version || vars.DEFAULT_CORE_IMAGE_TAG }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Run Core integration tests
        env:
          CORE_URL: ${{ steps.setup-core.outputs.service_url }}
        run: |
          pytest -o log_cli=true -o log_cli_level=INFO tests/integration -k "core" --alluredir=allure-results

      # Need to pull the pages branch in order to fetch the previous runs
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
            ref: gh-pages
            path: gh-pages

      - name: Allure Report
        uses: firebolt-db/action-allure-report@v1
        if: always()
        with:
            github-key: ${{ secrets.GITHUB_TOKEN }}
            test-type: integration
            allure-dir: allure-results
            pages-branch: gh-pages
            repository-name: firebolt-sqlalchemy
