# This workflow will install Python dependencies, run pre-commit checks, and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files

    - name: Type check with mypy
      run: |
        # Remove missing import override after firebolt-sdk release 0.2.1+
        mypy --ignore-missing-imports src

    - name: Test with pytest
      run: |
        pytest tests/unit
        
    - name: Convetional Commits Pull Request Title
      uses: jef/conventional-commits-pr-action@v1.0.0
      if: github.event_name == 'pull_request'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
